---
Name: exodus-config
#After:
#  - 'framework/*'
#  - 'cms/*'
---

PhpTek\Exodus\Task\StaticSiteRewriteLinksTask:
  log_file: '/var/tmp/failed-rewrite.log'

PhpTek\Exodus\Tool\StaticSiteContentExtractor:
  log_file: '/var/tmp/crawl-and-import.log'

# Prevent File::updateFileSystem() messing with the connector's own versioning
SilverStripe\Assets\File:
  update_filesystem: false
