---
Name: exodus-config
---

PhpTek\Exodus\Task\StaticSiteRewriteLinksTask:
  log_file: '/tmp/exodus.log'

PhpTek\Exodus\Tool\StaticSiteUtils:
  log_file: '/tmp/exodus.log'

PhpTek\Exodus\Tool\StaticSiteContentExtractor:
  user_agent: 'phptek/silverstripe-exodus'

---
Only:
  environment: 'dev'
---
# Disable the uploaded-file authenticity check in dev (TODO: Add to docs)
SilverStripe\Assets\Upload_Validator:
  use_is_uploaded_file: false
