---
Name: exodus-config
---

PhpTek\Exodus\Task\StaticSiteRewriteLinksTask:
  log_file: '/tmp/exodus-failed-rewrite.log'

PhpTek\Exodus\Tool\StaticSiteUtils:
  log_file: '/tmp/exodus.log'

PhpTek\Exodus\Tool\StaticSiteContentExtractor:
  user_agent: 'phptek/silverstripe-exodus'

# Prevent File::updateFileSystem() messing with the connector's own versioning
SilverStripe\Assets\File:
  update_filesystem: false
